runtime: go114
default_expiration: 1d
instance_class: F1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: ./ynov-api-c369caf8204f.json
  GIN_MODE: release
  CLOUDSQL_CONNECTION_NAME: ynov-api:europe-west1:ynov-immo
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: root
  CLOUDSQL_DATABASE_NAME: ynov_immo

automatic_scaling:
  max_instances: 1

handlers:
- url: .*
  script: auto
  secure: always

