runtime: go114
default_expiration: 1d
instance_class: F1

env_variables:
  MYSQL_CONNECTION: root:root@unix(/cloudsql/ynov-api:europe-west1:ynov-immo)/ynov_immo
  GOOGLE_APPLICATION_CREDENTIALS: ./ynov-api-f0d1500a3602.json
  GIN_MODE: release

automatic_scaling:
  max_instances: 1

handlers:
- url: .*
  script: auto
  secure: always

